# quotes.py

# ==============================================================================
# 🌞 MANHÃ: HUMOR DE GAMEPLAY (100 Frases - Estilo ColaAI)
# ==============================================================================
MORNING_QUOTES = [
    # --- NOVAS ADIÇÕES (PEDIDOS ESPECÍFICOS) ---
    "A conquista Mestre da Avalon não foi uma missão, foi um massacre. Centenas de wipes, traumas profundos e Guardiões questionando sua própria existência. Respeito aos sobreviventes.",
    "Raid Épica? Você nem conseguiu fazer a raid normal sem wipar! Se enxerga, Guardião.",
    
    # --- FRASES DE GAMEPLAY (FILTRADAS) ---
    "Dizem que usar tonalizador preto ou vermelho aumenta o DPS em 5%. Não sou eu que inventei as regras, é a ciência do jogo.",
    "Atenção: Um Guardião bonito bate mais forte. Se você está morrendo muito, talvez seja hora de visitar a Ada-1 e repensar esse look.",
    "O Mestre Rahool me contou um segredo: o God Roll que você quer cai hoje... pro seu amigo que instalou o jogo ontem.",
    "Wipe faz parte da vida. O problema não é o wipe, é quando ele acontece porque alguém errou o pulo no puzzle pela décima vez.",
    "Você chama isso de 'Build'? Até um Dreg na ZME tem mais sinergia de mods que essa salada de frutas que você equipou.",
    "A mira assistida existe por um motivo, Guardião. Não tenha vergonha de admitir que sem ela você não acerta nem o chão.",
    "Não adianta ter 100 de Resiliência se você continua se jogando na frente dos foguetes do seu próprio time.",
    "Lembrete diário: O Meta muda, mas a sua habilidade de errar a Super no chefe continua consistente. Parabéns pela estabilidade!",
    "Se farmar fosse trabalho, você seria o funcionário do mês. Pena que o pagamento é em Lúmen que você não tem onde gastar.",
    "Aquele inimigo com 1 de vida que te matou no Crisol não é 'hacker'. Ele só tem uma cadeira gamer melhor que a sua.",
    "Dizem que a cada Tonalizador feio aplicado em uma armadura Exótica, um Fantasma perde as asas. Pense nas crianças.",
    "Otimismo é achar que vai fazer a Raid em 40 minutos com LFG. Realismo é separar 4 horas e um calmante.",
    "Sua armadura brilha mais que o Viajante, mas seu dano é menor que o de uma pistola branca. Prioridades, né?",
    "A 'Mecânica' da Raid não é sugestão, é regra. Ler o chat ou ouvir o líder também ajuda a não explodir o time todo.",
    "Hoje é um ótimo dia para dropar aquela Exótica que você já tem 3 cópias no cofre. O RNG é uma benção!",
    "Seu Fantasma me disse que está cansado de te reviver em lugares estúpidos. Tente pular melhor hoje.",
    "Lúmen não compra habilidade, mas compra contratos. Vá trabalhar, Guardião!",
    "Aquele Tita comendo giz de cera no canto da Torre tem um K/D maior que o seu. Reflita.",
    "Arcanos: Lembrem-se que o pulo de vocês é, na verdade, uma queda com estilo. Cuidado com os buracos.",
    "Caçadores: Capas bonitas não protegem contra tiros de sniper. Usem cobertura.",
    "Não culpe os Arquitetos pela sua morte. A pedra estava lá, você que tropeçou nela.",
    "Sua nave de carregamento é mais rápida que seu tempo de reação no Crisol.",
    "O Banshee-44 esqueceu quantas vezes você já pediu a mesma arma, mas nós não esquecemos.",
    "Hoje é dia de limpar o Cofre! (Mentira, você vai guardar mais 10 armas inúteis 'só por garantia').",
    "A Treva oferece poder. A Luz oferece vida. O Eververso oferece danças. Escolha onde gastar seu tempo.",
    "Se a vida te der limões, jogue granadas. Se a vida te der erro Weasel, vá tomar um café.",
    "Raid no Dia 1 é para os fortes. Raid no dia 100 e ainda wipando no primeiro boss é para você.",
    "Aquele tiro de Sniper passou longe, hein? Até o inimigo parou pra rir.",
    "Use seu Super! Guardar Super pra próxima partida não rende juros no banco da Torre.",
    "O chão é lava? Não, o chão é seguro. Pare de pular na frente dos tiros do seu time.",
    "A Vanguarda relata que a taxa de 'Mortes por Arquitetos' subiu 200% quando você logou.",
    "Você não precisa ser o melhor, só precisa ser mais rápido que o amigo do lado quando o Ogro aparecer.",
    "Seu clã precisa de você. Nem que seja para servir de isca enquanto os bons jogam.",
    "A única coisa lendária sobre você hoje é a sua capacidade de errar granadas.",
    "Modificadores de atividade: 'Blackout'. Modificadores da sua vida: 'Preguiça'.",
    "Não existe 'KS' (Kill Steal), existe 'Confirmação de Baixa'. Roube aquela kill sem culpa!",
    "Sua build de corpo a corpo é ótima, exceto quando o boss voa ou explode. Detalhes.",
    "O Shaxx gritou tanto que ficou sem voz, e você ainda não capturou a zona B.",
    "Gambit: O modo onde você descobre o quanto odeia seus aleatórios e invasores com Xenofagia.",
    "Seu pardal tem buzina, use-a para irritar os amigos. É para isso que serve.",
    "Nada une mais um time do que culpar o 'lag' por um erro coletivo.",
    "A Torre é alta, mas a sua queda de produtividade quando o jogo atualiza é maior.",
    "Se você gastasse o tempo que gasta escolhendo shaders treinando mira, seria Pro Player.",
    "A Ada-1 pediu para você parar de usar essas cores. Está ofendendo o telar.",
    "Sua conexão caiu ou você deu Rage Quit? O sistema sabe, Guardião. O sistema sabe.",
    "O drifter come coisas nojentas, mas a coisa mais feia que ele viu hoje foi seu loadout.",
    "Parabéns! Você sobreviveu 5 minutos sem morrer. Novo recorde pessoal.",
    "Aquele Engrama Exótico no chão? Provavelmente é uma armadura de perna com status 58. Sinto muito.",
    "Não se preocupe, o boss tinha 1% de vida. O fato de você ter morrido com a Super cheia é só um detalhe.",
    "Códigos de erro: Baboon, Anteater, Weasel. Os verdadeiros inimigos finais de Destiny.",
    "Você é a prova viva de que a Luz pode reviver qualquer um, mesmo quem não merece.",
    "Seu K/D é negativo, mas sua atitude é positiva! (Mentira, você xingou o time todo).",
    "Aquele momento constrangedor quando você erra o pulo e o time todo está te assistindo no espectador.",
    "Eu vi Dregs com melhor pontaria que você. E eles têm quatro braços para coordenar.",
    "Hoje o dia está lindo para ser carregado pelos amigos na atividade difícil, não acha?",
    "A 'Divindade' é uma arma, não um pedido de socorro. Use-a direito.",
    "Cuidado com o Telesto. Ele pode quebrar o jogo, seu PC e a realidade a qualquer momento.",
    "Você diz que é 'Main Arcano', mas errou aquela Nova Bomb na parede. Suspeito.",
    "Titãs, lembrem-se: Socar o Boss que explode não é estratégia, é suicídio.",
    "Caçadores, sua capa prendeu na porta. Menos drama, mais tiro.",
    "O pós-jogo não perdoa. Vá farmar materiais ou fique para trás.",
    "Sua build de suporte é curar o inimigo errando tiros? Interessante.",
    "A Torre pede silêncio, mas seu visual 'neon radioativo' grita muito alto.",
    "Seu inventário está cheio. O correio está cheio. Sua paciência está vazia. O ciclo da vida.",
    "Nada como um bom erro 'Contacting Destiny Servers' para testar sua fé na Luz.",
    "Você tem 3 personagens, mas joga mal com todos. Isso que é consistência!",
    "O Zavala perguntou se você está em greve, porque não viu nenhuma baixa sua no relatório.",
    "A Eris Morn sorriu hoje. Isso significa que algo terrível vai acontecer com seu loot.",
    "Não subestime os Psions. Eles te empurram do mapa, você chora, eles riem.",
    "Seu lança-granadas tem 'Auto-Loading'? Porque sua habilidade de recarregar manualmente é lenta demais.",
    "Aquele momento em que você solta a Super e a 'cutscene' do boss começa. Clássico.",
    "Você não é AFK, você é 'Estrategicamente Estático'.",
    "Seu Pardal é rápido, pena que você bate em todas as árvores do caminho.",
    "O Saint-14 ama os pombos. Você joga como um pombo: voa, caga em tudo e vai embora.",
    "A 'Lógica da Espada' diz que você deve provar sua existência matando. Você está quase deixando de existir.",
    "A única coisa 'Obra-Prima' no seu inventário é a sua desculpa para não jogar bem.",
    "Sua build de estase é fria, mas seu desempenho é morno.",
    "Use o microfone. Ninguém lê chat no meio do tiroteio, gênio.",
    "Aquele emote foi caro. Pena que você morreu antes de terminar a animação.",
    "O Saladino chamou. Disse que os lobos dele jogam melhor que você.",
    "O Corvo está deprimido. Vendo você jogar, eu entendo ele.",
    "A única coisa que você 'soleou' foi a fila de login.",
    "Seu nível de luz é alto, mas sua luz interior está piscando.",
    "Achei que o nerf tinha sido na arma, não nas suas mãos.",
    "Você não precisa de cura, precisa de um milagre.",
    "O Viajante acordou só para ver você errar esse tiro?",
    "Seu clã tem um lema: 'Pelo menos tentamos'.",
    "A Vanguarda agradece seu serviço (mesmo que seja servindo de alvo).",
    "Hoje é dia de farmar Lúmen até o dedo cair.",
    "O dia está perfeito para ignorar objetivos e caçar kills, né? Típico.",
    "A única Raid que você completa rápido é a 'Raid à Geladeira' durante o loading.",
    "Sua conexão é discada ou os Vex estão manipulando o tempo de novo?",
    "Olhos para cima, Guardião. O chão já está cheio de marcas da sua cara.",
    "Vamos lá, mais uma tentativa. Dessa vez tenta ligar o monitor.",
    "O saque é aleatório, mas sua incompetência é constante. Bom dia!",
    "Se você não limpar os adds, os adds vão limpar você. Matemática simples.",
    "Eu aposto 100 Lúmens que você esqueceu de comprar os contratos do dia.",
    "Sua nave é exótica, seu pardal é exótico, sua habilidade é... comum.",
    "A Treva sussurra... 'você esqueceu de recarregar a arma'.",
    "Não corra na frente do Titã com a espada. Apenas não.",
    "Aquele baú secreto que você perdeu tinha um item azul. Não chore.",
    "O universo é vasto, mas a sua zona de conforto é o respawn.",
    "Você joga Destiny 2 ou 'Simulador de Inventário'?",
    "Seus inimigos têm barra de vida. Você tem barra de paciência. A sua acaba primeiro."
]

# ==============================================================================
# 🌇 TARDE: DETALHES DA LORE INSURGENTES (50 Quotes Canônicas)
# ==============================================================================
LORE_QUOTES = [
    "🧠 **Detalhes da Lore Insurgentes:** ||A grande reviravolta sobre Dredgen Bael é que ele não é um Guardião. Ele é um humano comum, filho de um armeiro da Tex Mechanica, que utiliza tecnologia proibida dos Nove para enfrentar a Vanguarda.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A 'Estação Nightfall' foi projetada para disparar uma onda de 'energia de eclipse'. Essa energia tem a capacidade aterrorizante de sufocar tanto a Luz quanto a Treva, reduzindo Guardiões a cascas vazias.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Blue (Jururu), a Fantasma do Drifter, revela que não falava há anos por escolha própria. Ela sacrificou seus processadores vocais no passado para salvar o Drifter, gerando um ressentimento silencioso entre os dois.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||O antagonista cósmico é 'Six' (Seis), um membro dos Nove. Diferente de seus irmãos, Six quer usar a morte em massa de portadores da Luz para gerar poder suficiente e abrir um portal de fuga desta dimensão.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A Ordem Práxica acidentalmente facilitou a ascensão de Bael. Ao manterem artefatos das Trevas em segredo em seus cofres sem compreendê-los, permitiram que Six corrompesse Bael dentro de suas próprias instalações.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||O Premier Lume era originalmente conhecido como Bracus Lume. Ele desapareceu com protótipos navais da Cidade há 3 anos, mas graças à dilatação temporal dos Nove, teve décadas para construir o Imperium.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A motivação do Drifter para se infiltrar na tripulação de Bael foi uma visão implantada pelos Nove. Nela, ele via Eris Morn sendo ferida mortalmente, e agiu para impedir esse futuro a qualquer custo.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Bael acredita que os Guardiões não deveriam governar a humanidade. Ele vê a Vanguarda como uma 'ditadura imortal' e acredita que os humanos comuns devem recuperar o controle de seu próprio destino.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||No final, descobre-se que a 'arma' escolhida pelo voto dos Nove não era Bael. Ele era apenas uma ferramenta descartável para Six. A verdadeira arma profetizada para encerrar o conflito era o Guardião (você).||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Aunor, uma Arcana da Ordem Práxica, começa a campanha rígida, mas termina admitindo que a tradição deve mudar. Ela concede o Selo Cormorant ao Guardião, aceitando o uso do equilíbrio entre Luz e Treva.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||O ataque inicial em Tharsis dizimou dezenas de Guardiões e Fantasmas. A energia de eclipse da Estação Nightfall anulou seus poderes instantaneamente, deixando apenas armaduras vazias para trás.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Servir como receptáculo para Six causa agonia física constante em Bael. Ele descreve a sensação como fogo e pressão interna, mas aceita a dor como prova de que é necessário para a causa.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||O Imperium Cabal de Lume não usa apenas força bruta; eles empregam tecnologia experimental roubada de conferências da Última Cidade, combinada com os presentes paracausais dos Nove.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Drifter executa seu plano de traição no momento final, tentando eliminar Bael para salvar sua tripulação. Bael sobrevive e foge, jurando que sua vingança será doce no futuro.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A profecia entregue pela Emissária (Orin) após a morte de um dos Nove era clara e aterrorizante: 'Aprisionem os Nove ou enfrentem a extinção universal'. A Vanguarda ocultou isso do povo.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Para consertar Blue e fazê-la falar novamente, o Guardião precisou caçar peças no mercado negro de Tharsis, lidando com sindicatos criminosos como os 'Pikers'.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Durante o confronto, Bael usa uma lâmina capaz de canalizar energia dos Nove. Mesmo sendo mortal, essa tecnologia permite que ele enfrente Guardiões como Aunor em combate direto.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||O nome da espécie Cabal é revelado como 'Barren' (Estéril) em diálogos da campanha, sugerindo que 'Cabal' é apenas um título político ou militar que usamos para eles.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A Singularidade de Kepler, vista em expansões anteriores, foi confirmada como a primeira tentativa falha dos Nove de criar uma saída deste universo, antes de tentarem usar a Estação Nightfall.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Drifter mentiu para todos, inclusive para nós, sobre suas intenções. Ele fingiu lealdade a Bael até o último segundo para garantir que Eris e os outros estivessem a salvo.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Lume chama Bael de 'Dredgen' com reverência suprema. Para o Imperium, o título não é de um renegado, mas de um líder messiânico escolhido por entidades cósmicas.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A Estação Nightfall utilizava 'coletores anti-bariônicos' para acumular energia. O plano era usar a morte dos Guardiões como bateria para rasgar a realidade e libertar Six.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||O Aranha (Spider) tentou lucrar com a guerra, mas sua barcaça foi abatida pelo Imperium e caiu nas areias de Marte. Ele fugiu, deixando o Guardião para limpar a bagunça.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Os Nove estão divididos. A facção conhecida como 'Outros' (Outer Nine), liderada por Six, não se importa com a vida humana e busca apenas sua própria libertação, custe o que custar.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Aunor revela que investigou o Drifter por anos. Ela conhece seus truques, mas acaba colaborando com ele, provando que a ameaça de Bael era grande demais para rivalidades antigas.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A energia de eclipse não é apenas escuridão; ela 'nega' a paracausalidade. Em Tharsis, ela impediu que os Fantasmas ressuscitassem seus Guardiões, matando-os permanentemente.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Ido, a escriba e parceira de Eris, usou seu conhecimento para rastrear a assinatura de energia dos Nove em Marte, provando ser vital para a inteligência da operação.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Drifter chama sua Fantasma de 'Blue' ironicamente. O nome sugere calma, mas a personalidade dela sempre foi difícil e, segundo ele, nada ensolarada.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Zavala admite sentir nostalgia pelas primeiras guerras em Marte. Ele vê o conflito com o Imperium como um retorno aos 'bons tempos' de combate direto contra a Legião Vermelha.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Os 'Pikers' são um sindicato de Eliksni ateus. Eles rejeitam a adoração à Grande Máquina (Viajante) e confiam apenas em tecnologia e contrabando para sobreviver em Tharsis.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A 'Divisão Totalidade' é a tropa de elite de Lume. Eles protegem os segredos do Imperium e foram os responsáveis por manter a Estação Nightfall operante.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Bael acredita que a imortalidade estagnou a humanidade. Para ele, a morte dá significado à vida, e os Guardiões, ao não morrerem, perderam sua humanidade.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A voz de Six é ouvida através de Bael, mas causa danos físicos ao hospedeiro. O humano tosse e sofre cada vez que a entidade fala por seus lábios.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Lume reconhece o Guardião como 'Arma Oposta' (Opposed Weapon). Ele nos vê como o único obstáculo real aos planos dos Nove, oferecendo até um lugar em sua legião.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A Imperatriz Caiatl possuía códigos de criptografia chamados 'anti-Fantasma'. O Imperium roubou essa tecnologia para impedir que nós hackeássemos seus sistemas facilmente.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Em um momento crucial, Drifter diz a Bael que sua dor não tem propósito, é apenas consequência. Isso abala a fé do vilão, que acreditava estar sofrendo por um bem maior.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Blue admite que Drifter a magoou profundamente no passado, mas decide lutar ao lado dele. A relação deles é de uma família disfuncional que se protege no fim das contas.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Para invadir a nave capitânia de Lume, o Guardião e a equipe utilizam uniformes roubados do Imperium, em uma missão de infiltração clássica.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A sequência de fuga da Estação Nightfall envolve o Guardião pilotando um veículo similar a um Pardal por dentro da estrutura da estação enquanto ela colapsa.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A destruição da Estação Nightfall gerou uma onda de choque que foi sentida por todos os portadores da Luz, um momento de silêncio psíquico que salvou a Terra.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Após a campanha, a Vanguarda retira as acusações contra o Drifter. Ele decide deixar a política da Cidade de lado e focar em caçar outros Dredgens corrompidos.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||O pai de Bael trabalhava na fundição de armas Tex Mechanica. Isso explica o acesso de Bael a armamentos de ponta e seu conhecimento técnico sobre como matar Guardiões.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A profecia 'Aprisione os Nove' sugere que não podemos matá-los, pois são fundamentais para a gravidade do sistema, mas devemos limitar sua influência física.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Tharsis é descrita como uma fronteira sem lei, um lugar onde a Vanguarda não tem poder e onde sindicatos e Vex independentes operam livremente.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Os Vex da 'Reforma de Tharsis' são únicos: desconectados da mente coletiva principal, eles desenvolveram um comportamento estranho, demonstrando interesse em jogos de azar.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Aunor afirma que a justiça não é cega, 'ela tem mira térmica'. Isso resume sua filosofia de caçar ameaças internas com precisão implacável.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Ao final, Drifter é visto bebendo sozinho no bar da Torre. Apesar da vitória, ele permanece um solitário, observando o Viajante com desconfiança.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Bael escapa usando um teletransporte desconhecido dos Nove, deixando claro que a ameaça do Imperium não acabou, apenas foi adiada.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||A campanha termina com um aviso: células de 'Guardiões das Trevas' e simpatizantes de Bael estão começando a despertar em todo o sistema solar.||",
    "🧠 **Detalhes da Lore Insurgentes:** ||Blue diz a frase marcante: 'Nunca confie num Dredgen... exceto no Drifter, às vezes'. Isso mostra que ela finalmente aceitou a natureza caótica de seu Guardião.||"
]
